spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_test?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: Black
    password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl